site_name: tokenwiser
site_description: Bag of, not Words, but Tricks!
nav:
  - Index: index.md
  - API: api.md
  
theme:
  name: material
  font: 
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - toc.follow
    - toc.integrate 
    - content.action.edit
    - content.code.copy
    - content.code.annotate 
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: grey
      accent: light green
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: grey
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [lazylines]
          options:
              show_source: True
              show_root_heading: True
              show_object_full_path: False
              show_category_heading: False
              show_bases: False
              show_submodules: False
              show_if_no_docstring: False
              show_signature: True
              heading_level: 2
              filters: ["!^_"]
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
repo_url: https://github.com/koaning/lazylines
extra_css:
  - stylesheets/extra.css